" Ensure vim-plug is installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fsSL -o ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Create the plugin directory
call plug#begin('~/.vim/plugged')

" Import all plugins
source ~/.vim/config/plugins.vim

" Initialize the plugin system
call plug#end()

" Source the main vimrc config
source ~/.vim/config/main.vim
