return {
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "main",
    lazy = false,
    build = ":TSUpdate",
    cmd = { "TSInstall", "TSUpdate", "TSUpdateSync", "TSUninstall", "TSLog" },
    config = function()
      require("nvim-treesitter").install({
        "asm",
        "awk",
        "bash",
        "bibtex",
        "c_sharp",
        "c",
        "cairo",
        "clojure",
        "cmake",
        "commonlisp",
        "cpp",
        "css",
        "csv",
        "cuda",
        "cue",
        "d",
        "dart",
        "desktop",
        "devicetree",
        "diff",
        "disassembly",
        "dockerfile",
        "dot",
        "ebnf",
        "editorconfig",
        "elixir",
        "erlang",
        "fish",
        "fsh",
        "fsharp",
        "func",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "glsl",
        "gnuplot",
        "go",
        "goctl",
        "gomod",
        "gosum",
        "gotmpl",
        "gowork",
        "gpg",
        "groovy",
        "haskell",
        "hcl",
        "hlsl",
        "html",
        "http",
        "java",
        "javadoc",
        "javascript",
        "jinja_inline",
        "jinja",
        "jq",
        "jsdoc",
        "json",
        "json5",
        "jsonnet",
        "julia",
        "kcl",
        "kconfig",
        "kdl",
        "kotlin",
        "latex",
        "linkerscript",
        "llvm",
        "lua",
        "luadoc",
        "luap",
        "make",
        "markdown_inline",
        "markdown",
        "matlab",
        "meson",
        "nasm",
        "nginx",
        "objc",
        "objdump",
        "ocaml_interface",
        "ocaml",
        "ocamllex",
        "pascal",
        "passwd",
        "pem",
        "perl",
        "php",
        "powershell",
        "printf",
        "prolog",
        "promql",
        "properties",
        "proto",
        "prql",
        "puppet",
        "pymanifest",
        "python",
        "ql",
        "r",
        "readline",
        "regex",
        "rego",
        "requirements",
        "ruby",
        "rust",
        "scala",
        "scss",
        "solidity",
        "sql",
        "ssh_config",
        "strace",
        "tcl",
        "terraform",
        "tmux",
        "toml",
        "tsv",
        "tsx",
        "twig",
        "typescript",
        "typespec",
        "udev",
        "vhdl",
        "vim",
        "vimdoc",
        "xml",
        "xresources",
        "yaml",
      })

      -- Parse Helm as Go template
      vim.treesitter.language.register("gotmpl", "helm")

      -- Enable highlight + indent per-buffer on FileType
      vim.api.nvim_create_autocmd("FileType", {
        callback = function(args)
          local buf = args.buf
          local ft = vim.bo[buf].filetype
          local lang = vim.treesitter.language.get_lang(ft) or ft
          if not pcall(vim.treesitter.start, buf, lang) then
            return
          end
          vim.bo[buf].indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
        end,
      })
    end,
  },
}
